/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_ring_buffer_init();
extern void test_ring_buffer_add_one_element();
extern void test_ring_buffer_fill_the_buffer();
extern void test_ring_buffer_fill_the_buffer_plus_one();
extern void test_ring_buffer_read_one_element();
extern void test_ring_buffer_store_10_read_5();
extern void test_ring_buffer_store_ring_buffer_size_plus_2_and_read_5();
extern void test_ring_buffer_get_min_max();


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_ring_buffer.c");
  run_test(test_ring_buffer_init, "test_ring_buffer_init", 24);
  run_test(test_ring_buffer_add_one_element, "test_ring_buffer_add_one_element", 32);
  run_test(test_ring_buffer_fill_the_buffer, "test_ring_buffer_fill_the_buffer", 45);
  run_test(test_ring_buffer_fill_the_buffer_plus_one, "test_ring_buffer_fill_the_buffer_plus_one", 61);
  run_test(test_ring_buffer_read_one_element, "test_ring_buffer_read_one_element", 77);
  run_test(test_ring_buffer_store_10_read_5, "test_ring_buffer_store_10_read_5", 93);
  run_test(test_ring_buffer_store_ring_buffer_size_plus_2_and_read_5, "test_ring_buffer_store_ring_buffer_size_plus_2_and_read_5", 127);
  run_test(test_ring_buffer_get_min_max, "test_ring_buffer_get_min_max", 166);

  return UnityEnd();
}
